[CHORE] 3주차 과제 완료
AND-SOPT-ANDROID/minseo-song pull request #6
Opened 2024-11-01 13:26 UTC by MinseoSONG

## Related issue 🛠
- closed #5 3차 과제 완료

## Work Description ✏️
- [💡3주차 과제](https://astonishing-knee-571.notion.site/3-130f7ae2828f80e9850bcef34befcda7?pvs=4)
- [x] 공통 컴포넌트 찾기
- [x] 뷰 스케치 및 각 화면 컴포넌트화
- [x] UI 로직 설계
- [x] 코드 수정

## Screenshot 📸
<img src="" width="360"/>

## Uncompleted Tasks 😅

## To Reviewers 📢
- 아직 공통 컴포넌트 찾고 패키지 분리하고 로직 설계하는 .. 여러모로 많이 부족한 것 같아서 많은 조언 부탁드립니다 !

2024-11-03 09:50 UTC, beom84 approved these changes
3차과제 고생하셨습니다

2024-11-03 09:50 UTC, beom84 commented on app/src/main/java/org/sopt/and/navigate/NavGraph.kt
Mypage 부터 시작하는건가요?

2024-11-03 09:50 UTC, beom84 commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +                IconWithTitle(
여기서만 사용한다면 component를  myscreen으로 옮겨도 되지않을까요?

2024-11-03 12:14 UTC, wjdrjs00 approved these changes
3주차 고생 많으셨습니다!!
컴포넌트화를 통해 코드 수가 많이 줄어드는 것이 인상 깊습니다!!!

2024-11-03 12:14 UTC, wjdrjs00 commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +                IconWithTitle(
이 부분은 취향 차이가 크지 않을까? 조심스럽게 남겨봅니다!!
전 해당화면에서만 사용하더라도 중복되면 컴포넌트로 분리도 좀 더 보기 편하다 생각하는 쪽? 입니다 ㅎㅎㅋ

2024-11-03 14:24 UTC, Hyobeen-Park reviewed
새롭게 만든 컴포넌트들도 패키지를 찾아주면 나중에 찾기 더 편해질 것 같아요!! 3차 과제 수고 많으셨습니다😊

2024-11-03 14:24 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/navigate/NavGraph.kt
> +    NavHost(navController = navController, startDestination = Routes.My.route){
이거 SignIn에서 시작해야 하는 것 같아요..!!

2024-11-03 14:24 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/component/IconWithText.kt
> +    icon: Painter,
아이콘을 Painter로 받는 이유가 궁금해요!!

2024-11-03 14:24 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +                IconWithTitle(
패키지 분리는 정말 정답이 없는 것 같아요!! 저는 보통 

- 여러 스크린에서 사용되는 경우 -> component
- 한 스크린에서 여러 번 사용되는 경우 -> screen/component

이렇게 패키지를 나누려고 하는 편입니다!!

2024-11-03 14:24 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
>      signUpViewModel: SignUpViewModel
`SignInScreen`에서 `SignUpViewModel`까지 받아오게 데이터 전달 외에 다른 이유가 있을까요? 오로지 userInfo를 받아오기 위함이라면 뷰모델을 넘기는 것이 아닌 데이터만 넘기는 방법으로 구현하는 것이 더 좋아보여서요..!!

2024-11-03 14:24 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/signin/SignInViewModel.kt
>      val snackbarMessage: StateFlow<String?> get() = _snackbarMessage
`mutableState`와 `mutableStateFlow`의 차이점은 무엇일까요? 그리고 `passwordVisible`은 `mutableState`로, `snackbarMessage`는 `mutableStateFlow`로 선언하신 이유가 궁금합니다!

2024-11-03 14:24 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/signin/SignInViewModel.kt
>      }
저는 `passwordVisible `관리도 `passwordTextfield `컴포넌트 내부로 넣었어요! 이런 방법도 있다는 점 슬쩍 전달드립니다ㅎㅎ 지금처럼 뷰모델에서 관리해도 괜찮지만 SignUpScreen은 뷰모델이 아닌 screen에서 관리하고 계신 것 같아서 이 부분은 한 가지 방법으로 통일하면 좋을 것 같아요!

그리고 사소하긴 하지만 변수 명을 지을 때 저는 `isPasswordVisible `또는 `passwordVisibility`로 짓는 것을 더 선호하는 편입니다ㅎㅎ

2024-11-04 16:43 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/navigate/NavGraph.kt
아이고 테스트한다고 바꿔놨었는데 깜빡했네유

2024-11-04 18:05 UTC, l2hyunwoo requested changes
고생하셨습니다.

2024-11-04 18:05 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/IconWithText.kt
> +    icon: Painter,
Painter는 컴포저블 함수의 패러미터 타입으로 사용하는 것을 지양하고 있는데 그 이유에 대해서 알고 계실까요?

2024-11-04 18:05 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/IconWithText.kt
> +fun IconWithText(
`IconWithText` 라는 것이 어떤 역할을 나타내는지 잘 모르겠습니다. 기능에 맞춰서 작명하는 것을 권장합니다.

2024-11-04 18:05 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/IconWithTitle.kt
> +    onClick: ()->Unit
```suggestion
    onClick: () -> Unit
```

Command + Option + L (Ctrl + Alt + L) 누르시면 자동정렬 됩니다!

2024-11-04 18:05 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/IconWithTitle.kt
> +        ) {
이 사이에는 따로 Spacing 안두시나요?

2024-11-04 18:05 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +                }
스크린이 아닌 Action에 대한 콜백함수는 이렇게 trailing lambda를 사용하지 마시고 naming parameter를 사용해주시기 바랍니다. 컴포즈 함수에서 trailing lambda는 대개 자식 컴포넌트가 들어오는 컨텐트 컴포저블로 사용하기 때문에 사용시 혼란을 줄 수 있습니다.

2024-11-04 18:05 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +                }
여기도...

2024-11-04 18:05 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
>      signUpViewModel: SignUpViewModel
뷰모델을 두개를 사용하신 이유가 있을까요?

2024-11-06 05:49 UTC, jihyunniiii reviewed
UI 로직 설계를 엄청 엄청 꼼꼼하게 잘 해주셨네요!
고생하셨습니다 ~

2024-11-06 05:49 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/component/MyPageList.kt
> +fun MyPageList(
List가 아니라 그 내부에 들어가는 아이템인 것 같아요.
List 보다는 다른 직관적인 네이밍을 사용하시는 게 좋을 것 같습니다.

2024-11-06 05:49 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
>                      .verticalScroll(scrollState)
LazyColumn을 사용하시는 것이 성능상으로 더 좋을 것 같아요!
이유는! 왤까요?

2024-11-06 05:49 UTC, jihyunniiii commented on app/src/main/java/org/sopt/and/ui/signup/SignUpViewModel.kt
>  val PASSWORD_REGEX = Regex("^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@\$!%*?&])[A-Za-z\\d@\$!%*?&]{$PASSWORD_MIN_LENGTH,$PASSWORD_MAX_LENGTH}\$")
전역으로 선언하신 이유가 있나요?

2024-11-07 18:11 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +                IconWithTitle(
한 스크린에서 여러 번 사용되는 경우 -> screen/component

기억해두겠습니다 !

2024-11-07 18:12 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/navigate/NavGraph.kt
> +    NavHost(navController = navController, startDestination = Routes.My.route){
아이코 깜빡했어요 바로 수정하겠습니다 !

2024-11-07 18:14 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
>      signUpViewModel: SignUpViewModel
헉 데이터만 넘기는 방법을 생각 못했어요 🥹
뷰모델로 데이터를 저장하니까 넘겨주는 것도 받아오는 것도 모두 뷰모델로 해야겠다고 생각해버린 ㅠㅠ .. 수정하겠습니다 !

2024-11-07 18:22 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/component/IconWithText.kt
> +    icon: Painter,
어 .. 그냥 바로 Image의 painter 인자에 넣어주려고 그랬던 거였는데 찾아보니 지양하는 방법이였군요 🥲 새로운 지식 !

2024-11-07 18:33 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/signin/SignInViewModel.kt
>      val snackbarMessage: StateFlow<String?> get() = _snackbarMessage
mutableState는 상태 관리를 위해 사용되는 객체로, 특정 값의 변경을 감지하여 UI를 자동으로 리컴포지션하게 해주는데
mutableStateFlow는 Flow 기반 상태 관리 도구로, 상태 흐름을 비동기적으로 처리한다고 알고 있습니다 !

그래서 passwordVisible은 UI 상태에만 국한되어 있으니까 비동기 작업이 필요없다고 생각해서 mutableState를 사용했고, snackbarMessage는 UI 상태와 직접적으로 관련된 거라기보다는 비동기적으로 처리되는 상황에 따라 나타나거나 사라져야 하니까 mutableStateFlow를 사용했습니다 !
혹시 틀린 점이나 굳이 이럴 필요없이 통일할 수 있다면 말씀해주세용 .. 🥹

2024-11-07 18:35 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/signin/SignInViewModel.kt
>      }
헉 참고해서 수정하겠습니다 !

2024-11-10 17:49 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/component/IconWithTitle.kt
> +    onClick: ()->Unit
앗 자동정렬을 습관화해보겠습니다 ..!

2024-11-10 17:54 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/component/IconWithText.kt
> +    icon: Painter,
앗 .. 사실 지양하고 있는지도 모르고 있었어요 🥹
찾아보니
'컴포저블 함수의 인자는 주로 비즈니스 로직이나 외부 데이터가 전달되는 것이 이상적인데, Painter는 UI 요소와 직접적으로 관련된 세부 사항이기 때문에 지양한다'고 하네요 !
새로운 지식 감사합니다 !!

2024-11-10 18:00 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/component/IconWithText.kt
> +fun IconWithText(
항상 네이밍하는 것이 힘들어 그냥 나중에 찾아보기 쉽게 어떤 형식으로 존재하는지 위주로 네이밍하던게 습관이 되어버려서 .. 🥲 이제 기능에 맞춰서 작명해보겠습니다 !

2024-11-10 18:16 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/component/IconWithTitle.kt
> +        ) {
어 .. 뷰 상으로 봤을 때 굳이 필요하지 않아 보여서 넣지 않았는데 보통 구분을 위해서라도 넣는 편인가요??

2024-11-10 18:43 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +                }
헉 깊게 생각하지 않고 그냥 간단하게 쓰려다보니 저렇게 습관을 들여서 쓰고 있었는데 .. !
수정하겠습니다 정말 감사합니다 !!

2024-11-10 18:45 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
> +                }
넵 !

2024-11-10 18:47 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/signin/SignInScreen.kt
>      signUpViewModel: SignUpViewModel
데이터를 넘겨주기 위해 뷰모델을 두개를 사용했는데, 뷰모델로 데이터를 저장하니까 넘겨주는 것도 받아오는 것도 모두 뷰모델로 해야겠다고 생각해버려서 .. 데이터만 넘기는 방법을 생각 못했습니다 🥹
수정하겠습니다 !

2024-11-10 18:51 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/component/MyPageList.kt
> +fun MyPageList(
앗 넵 알겠습니다 수정하겠습니다 !

2024-11-10 18:55 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/my/MyScreen.kt
>                      .verticalScroll(scrollState)
Column과 verticalScroll을 사용하면 스크롤 영역 내의 모든 항목을 한번에 렌더링해야하는데, LazyColumn은 화면에 보이는 항목만 렌더링하기 때문 ! 인 것 같습니다 😀
감사합니다 ! 수정할게요 !!

2024-11-10 18:59 UTC, MinseoSONG commented on app/src/main/java/org/sopt/and/ui/signup/SignUpViewModel.kt
>  val PASSWORD_REGEX = Regex("^(?=.*[A-Za-z])(?=.*\\d)(?=.*[@\$!%*?&])[A-Za-z\\d@\$!%*?&]{$PASSWORD_MIN_LENGTH,$PASSWORD_MAX_LENGTH}\$")
원래 다른 파일에 있던 친구들을 데리고 온거라 .. 전역 상태 그대로 옮겨버렸네요 🥲
내부로 옮겨서 수정해보겠습니다 !

2024-11-13 09:25 UTC, Hyobeen-Park approved these changes

2024-11-13 09:27 UTC, merged

2024-11-13 13:04 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/and/component/IconWithTitle.kt
> +        ) {
보통은 디자이너하고 협의하에 스페이싱을 넣는데, 컴포넌트 간에 간격이 없으면 좀 답답해 보이더라구요

2024-11-13 13:26 UTC, Hyobeen-Park reviewed
아까 너무 급하게 어푸해서 다시 왔습니다😅 4차 과제도 화이팅!!

2024-11-13 13:26 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/component/BuyTextButton.kt
> +    onClick: ()->Unit
요기도 코드 정렬..!!!

2024-11-13 13:26 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/component/BuyTextButton.kt
> +                .clickable { onClick }
이거 onClick() 괄호 없이도 실행 되나요?!?? 항상 중괄호로 감쌀 때는 `.clickable { onclick() }`으로 사용했어서 궁금하네용

2024-11-13 13:26 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/component/MyPageItem.kt
> +    icon: Painter,
여기도 Painter 대신 아이콘 id 등을 받아오는 것이 좋을 것 같아요!

2024-11-13 13:26 UTC, Hyobeen-Park commented on app/src/main/java/org/sopt/and/ui/signin/SignInViewModel.kt
> +    var userInfo by mutableStateOf(UserInfo("", ""))
UserInfo에서 기본값을 주면 여기에서 UserInfo() 이렇게 선언할 수 있어요!